name: Dependency & Vulnerability Scan

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  scan:
    uses: JAYANTH-ORG/shared-librarys/.github/workflows/dependency-vuln-bot.yml@master
    # with:
      # Add any required inputs here
