name: Dependency & Vulnerability Scan
on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  fast-scan:
    uses: JAYANTH-ORG/shared-librarys/.github/workflows/fast-dependency-scan.yml@master
    with:
      scan-maven: true
      scan-npm: false
